Repository gazebosim/gz-transport, pull requests merged in 2020-07, with the labels that each got.

#149 Update deps for Dome: use msgs6
  .github/workflows/ci-bionic.yml
  CMakeLists.txt
  Changelog.md
  configure.bat
  docker/ign-transport/Dockerfile
Labels: 🔮 dome

#151 Remove Windows warnings
  log/src/CMakeLists.txt
  src/CMakeLists.txt
Labels: 🏰 citadel

#150 Remove warnings on Homebrew
  include/ignition/transport/Helpers.hh
  src/Node.cc
  src/NodeShared.cc
Labels: macOS, 🏰 citadel

#153 Helper function to get a valid topic name
  include/ignition/transport/TopicUtils.hh
  src/TopicUtils.cc
  src/TopicUtils_TEST.cc
Labels: 📜 blueprint
