Repository gazebosim/gz-transport, pull requests merged in 2020-08, with the labels that each got.

#158 Modernize actions CI
  .github/ci/packages.apt
  .github/workflows/ci-bionic.yml
  .github/workflows/ci.yml
Labels: 📜 blueprint

#160 Removed repeated installation instructions
  README.md
  tutorials/02_installation.md
Labels: documentation, 🔮 dome

#161 Removed markdown-header
  README.md
Labels: documentation, 🔮 dome

#164 Prevent empty messages from spamming the console.
  log/src/Log.cc
  log/src/Recorder.cc
Labels: 📜 blueprint

#159 Suppress focal-specific warnings
  CMakeLists.txt
  include/ignition/transport/Helpers.hh
  include/ignition/transport/config.hh.in
  log/src/Log_TEST.cc
  src/Node.cc
  src/NodeShared.cc
Labels: 🏰 citadel

#155 7 ➡️ 8
  .github/ci/packages.apt
  .github/workflows/ci-bionic.yml
  .github/workflows/ci.yml
  CMakeLists.txt
  Changelog.md
  include/ignition/transport/Helpers.hh
  include/ignition/transport/TopicUtils.hh
  include/ignition/transport/config.hh.in
  log/src/Log_TEST.cc
  src/CIface_TEST.cc
  src/Node.cc
  src/NodeShared.cc
  src/TopicUtils.cc
  src/TopicUtils_TEST.cc
Labels: 🏰 citadel

#167 8.1.0 prep
  CMakeLists.txt
  Changelog.md
Labels: 🏰 citadel
