Repository gazebosim/gz-transport, pull requests merged in 2020-09, with the labels that each got.

#168 7 ➡️ 8
  log/src/Log.cc
Labels: 🏰 citadel

#169 8 ➡️ 9
  .github/ci/packages.apt
  .github/workflows/ci-bionic.yml
  .github/workflows/ci.yml
  CMakeLists.txt
  Changelog.md
  example/publisher_c.cc
  include/ignition/transport/Discovery.hh
  include/ignition/transport/Helpers.hh
  include/ignition/transport/NetUtils.hh
  include/ignition/transport/Node.hh
  include/ignition/transport/NodeShared.hh
  include/ignition/transport/Packet.hh
  include/ignition/transport/TopicUtils.hh
  include/ignition/transport/TransportTypes.hh
  include/ignition/transport/config.hh.in
  log/include/ignition/transport/log/Recorder.hh
  log/src/CMakeLists.txt
  log/src/Log.cc
  log/src/Log_TEST.cc
  log/src/Recorder.cc
  log/src/Recorder_TEST.cc
  log/test/integration/recorder.cc
  src/CIface_TEST.cc
  src/CMakeLists.txt
  src/NetUtils.cc
  src/Node.cc
  src/NodeShared.cc
  src/NodeSharedPrivate.hh
  src/Node_TEST.cc
  src/TopicUtils.cc
  src/TopicUtils_TEST.cc
  tutorials/02_installation.md
  tutorials/20_env_variables.md
Labels: 🔮 dome

#152 One NodeShared per process
  include/ignition/transport/Helpers.hh
  src/Helpers.cc
  src/NodeShared.cc
Labels: 🏰 citadel

#172 8 ➡️ 9
  include/ignition/transport/Helpers.hh
  src/Helpers.cc
  src/NodeShared.cc
Labels: 🔮 dome

#173 Make CPPZMQ a PUBLIC dependency
  src/CMakeLists.txt
Labels: 🔮 dome

#174 Fix mem leak
  src/NodeShared.cc
Labels: 🏰 citadel

#175 Remove deprecations before 9.x.x release
  include/ignition/transport/AdvertiseOptions.hh
  include/ignition/transport/NodeShared.hh
  include/ignition/transport/Packet.hh
  include/ignition/transport/Publisher.hh
  src/AdvertiseOptions.cc
  src/AdvertiseOptions_TEST.cc
  src/NodeShared.cc
  src/Packet.cc
  src/Publisher.cc
Labels: 🔮 dome

#176 Disable flaky Mac OS X tests
  CMakeLists.txt
  log/test/integration/playback.cc
  log/test/integration/recorder.cc
  src/ign_TEST.cc
  test/integration/twoProcsPubSub.cc
Labels: 📜 blueprint

#177 7 -> 8
  CMakeLists.txt
  log/test/integration/playback.cc
  log/test/integration/recorder.cc
  src/ign_TEST.cc
  test/integration/twoProcsPubSub.cc
Labels: 🏰 citadel

#178 8 -> 9
  CMakeLists.txt
  log/test/integration/playback.cc
  log/test/integration/recorder.cc
  src/NodeShared.cc
  src/ign_TEST.cc
  test/integration/twoProcsPubSub.cc
Labels: beta, 🔮 dome

#179 Use private access modifier for pImpl variable in MsgIter class
  .github/workflows/ci.yml
  log/include/ignition/transport/log/MsgIter.hh
Labels: beta, 🔮 dome

#180 ⬆️ 9.0.0~pre2
  CMakeLists.txt
Labels: 🔮 dome

#181 Update link to the tutorials
  README.md
Labels: 🔮 dome

#182 Remove contribute tutorial
  tutorials/20_env_variables.md
  tutorials/21_contribute.md
  tutorials/22_development.md
Labels: 🔮 dome

#183 Fix link in "development" tutorial
  tutorials/22_development.md
Labels: 🔮 dome

#186 Corrected link address in development tutorial
  tutorials/22_development.md
Labels: 🔮 dome

#187 Changes from Dome tutorial party
  tutorials/02_installation.md
Labels: 🔮 dome
