Repository gazebosim/gz-transport, pull requests merged in 2021-05, with the labels that each got.

#237 Make zmq check for post 4.3.1 not to include 4.3.1
  include/ignition/transport/Helpers.hh
Labels: 🏢 edifice

#242 Port codecov to new configuration
  .github/workflows/ci.yml
Labels: 🏯 fortress

#246 Remove tools/code_check and update codecov
  .github/workflows/ci.yml
  CMakeLists.txt
  tools/check_test_ran.py
  tools/code_check.sh
  tools/cpplint.py
  tools/cpplint_to_cppcheckxml.py
Labels: 🏰 citadel

#245 Consider all network interfaces when checking HOST option.
  include/ignition/transport/Discovery.hh
Labels: 🔮 dome

#216 Add standalone executables
  conf/CMakeLists.txt
  configure.bat
  src/CMakeLists.txt
  src/cmd/CMakeLists.txt
  src/cmd/cmdtransport.rb.in
  src/cmd/ign.cc
  src/cmd/ign.hh
  src/cmd/ign_TEST.cc
  src/cmd/ign_src_TEST.cc
  src/cmd/service_main.cc
  src/cmd/topic_main.cc
Labels: 🏢 edifice
