Repository gazebosim/gz-transport, pull requests merged in 2021-04, with the labels that each got.

#241 Remove unnecessary copy and assignment operators
  include/ignition/transport/Publisher.hh
  src/Publisher.cc
Labels: 🏢 edifice

#240 Remove unnecessary copy and assignment operators
  include/ignition/transport/Publisher.hh
  src/Publisher.cc
Labels: 🏯 fortress

#239 👩‍🌾 Remove deprecated test
  test/regression/CMakeLists.txt
  test/regression/deprecated.cc
Labels: 🏰 citadel
