Repository gazebosim/gz-transport, pull requests merged in 2021-12, with the labels that each got.

#281 Documented the default value of IGN_PARTITION
  tutorials/20_env_variables.md
Labels: documentation, 🏰 citadel, Gazebo 1️1️

#283 8 ➡️ 9
  tutorials/20_env_variables.md
Labels: 🔮 dome

#284 🎈 9.1.2 🏁
  CMakeLists.txt
  Changelog.md
Labels: 🔮 dome

#285 Bumps in garden: use ign-math7
  .github/ci/packages.apt
  bitbucket-pipelines.yml
  docker/ign-transport/Dockerfile
Labels: needs upstream release, 🌱 garden
