Repository gazebosim/gz-transport, pull requests merged in 2022-03, with the labels that each got.

#293 Add Ubuntu Jammy CI
  .github/workflows/ci.yml
Labels: 🏯 fortress

#294 8 ➡️ 10
  Changelog.md
  include/ignition/transport/Discovery.hh
  src/NetUtils.cc
  tutorials/20_env_variables.md
Labels: 🏢 edifice

#288 Add option to output messages in JSON format
  src/cmd/ign.cc
  src/cmd/ign.hh
  src/cmd/ign_src_TEST.cc
  src/cmd/topic_main.cc
Labels: 🏢 edifice

#295 10 ➡️ 11
  Changelog.md
  include/ignition/transport/Discovery.hh
  src/Discovery.cc
  src/NetUtils.cc
  src/NodeShared.cc
  src/cmd/ign.cc
  src/cmd/ign.hh
  src/cmd/ign_src_TEST.cc
  src/cmd/topic_main.cc
  tutorials/20_env_variables.md
Labels: 🏯 fortress

#297 Remove Bionic from future releases (Garden+)
  .github/workflows/ci.yml
  README.md
  bitbucket-pipelines.yml
  docker/ign-transport/Dockerfile
  tutorials/02_installation.md
Labels: documentation, tests, 🌱 garden

#298 Focal CI: static checkers and doxygen linters
  .github/workflows/ci.yml
  include/ignition/transport/AdvertiseOptions.hh
  include/ignition/transport/CIface.h
  include/ignition/transport/Node.hh
  include/ignition/transport/NodeOptions.hh
  include/ignition/transport/NodeShared.hh
  include/ignition/transport/Publisher.hh
  include/ignition/transport/RepHandler.hh
  include/ignition/transport/ReqHandler.hh
  include/ignition/transport/TopicUtils.hh
  log/include/ignition/transport/log/MsgIter.hh
  log/include/ignition/transport/log/Playback.hh
  log/include/ignition/transport/log/QueryOptions.hh
  log/include/ignition/transport/log/SqlStatement.hh
  src/Publisher_TEST.cc
  tutorials/03_nodesAndTopics.md
  tutorials/21_contribute.md
Labels: 🏰 citadel, Gazebo 1️1️

#300 Use exec instead of popen to run CLI11 based binaries
  src/cmd/cmdtransport.rb.in
Labels: 🏢 edifice

#302 10 ➡️ 11
  .github/workflows/ci.yml
  Changelog.md
  include/ignition/transport/AdvertiseOptions.hh
  include/ignition/transport/CIface.h
  include/ignition/transport/Node.hh
  include/ignition/transport/NodeOptions.hh
  include/ignition/transport/NodeShared.hh
  include/ignition/transport/Publisher.hh
  include/ignition/transport/RepHandler.hh
  include/ignition/transport/ReqHandler.hh
  include/ignition/transport/TopicUtils.hh
  log/include/ignition/transport/log/MsgIter.hh
  log/include/ignition/transport/log/Playback.hh
  log/include/ignition/transport/log/QueryOptions.hh
  log/include/ignition/transport/log/SqlStatement.hh
  src/Publisher_TEST.cc
  src/cmd/cmdtransport.rb.in
  tutorials/03_nodesAndTopics.md
  tutorials/21_contribute.md
Labels: 🏯 fortress

#303 11 ➡️ 12 (main)
  .github/workflows/ci.yml
  Changelog.md
  include/ignition/transport/AdvertiseOptions.hh
  include/ignition/transport/CIface.h
  include/ignition/transport/Discovery.hh
  include/ignition/transport/Node.hh
  include/ignition/transport/NodeOptions.hh
  include/ignition/transport/NodeShared.hh
  include/ignition/transport/Publisher.hh
  include/ignition/transport/RepHandler.hh
  include/ignition/transport/ReqHandler.hh
  include/ignition/transport/TopicUtils.hh
  log/include/ignition/transport/log/MsgIter.hh
  log/include/ignition/transport/log/Playback.hh
  log/include/ignition/transport/log/QueryOptions.hh
  log/include/ignition/transport/log/SqlStatement.hh
  src/Discovery.cc
  src/NetUtils.cc
  src/NodeShared.cc
  src/Publisher_TEST.cc
  src/cmd/cmdtransport.rb.in
  src/cmd/ign.cc
  src/cmd/ign.hh
  src/cmd/ign_src_TEST.cc
  src/cmd/topic_main.cc
  tutorials/03_nodesAndTopics.md
  tutorials/20_env_variables.md
  tutorials/21_contribute.md
Labels: 🌱 garden
