Repository gazebosim/gz-transport, pull requests merged in 2022-06, with the labels that each got.

#317 🎈 11.1.0
  CMakeLists.txt
  Changelog.md
Labels: 🏯 fortress

#318 ign -> gz Environment Variable Migration : gz-transport
  Migration.md
  include/gz/transport/CIface.h
  include/gz/transport/Discovery.hh
  include/gz/transport/NodeOptions.hh
  log/test/integration/playback.cc
  log/test/integration/recorder.cc
  log/test/integration/topicChirp_aux.cc
  src/CIface_TEST.cc
  src/Discovery_TEST.cc
  src/NetUtils.cc
  src/NodeOptions.cc
  src/NodeOptions_TEST.cc
  src/NodeShared.cc
  src/Node_TEST.cc
  src/cmd/ign_TEST.cc
  src/cmd/ign_src_TEST.cc
  test/integration/authPubSub.cc
  test/integration/authPubSubSubscriberInvalid_aux.cc
  test/integration/fastPub_aux.cc
  test/integration/pub_aux.cc
  test/integration/pub_aux_throttled.cc
  test/integration/scopedTopic.cc
  test/integration/scopedTopicSubscriber_aux.cc
  test/integration/statistics.cc
  test/integration/twoProcsPubSub.cc
  test/integration/twoProcsPubSubSubscriber_aux.cc
  test/integration/twoProcsPublisher_aux.cc
  test/integration/twoProcsSrvCall.cc
  test/integration/twoProcsSrvCallReplierInc_aux.cc
  test/integration/twoProcsSrvCallReplier_aux.cc
  test/integration/twoProcsSrvCallStress.cc
  test/integration/twoProcsSrvCallSync1.cc
  test/integration/twoProcsSrvCallWithoutInput.cc
  test/integration/twoProcsSrvCallWithoutInputReplierInc_aux.cc
  test/integration/twoProcsSrvCallWithoutInputReplier_aux.cc
  test/integration/twoProcsSrvCallWithoutInputStress.cc
  test/integration/twoProcsSrvCallWithoutInputSync1.cc
  test/integration/twoProcsSrvCallWithoutOutput.cc
  test/integration/twoProcsSrvCallWithoutOutputReplierInc_aux.cc
  test/integration/twoProcsSrvCallWithoutOutputReplier_aux.cc
  test/integration/twoProcsSrvCallWithoutOutputStress.cc
  tutorials/03_nodesAndTopics.md
  tutorials/06_security.md
  tutorials/07_relay.md
  tutorials/20_env_variables.md
  tutorials/22_development.md
  tutorials/23_topic_statistics.md
Labels: 🌱 garden, ign to gz

#312 Bash completion for flags
  CMakeLists.txt
  log/test/integration/CMakeLists.txt
  src/CMakeLists.txt
  src/cmd/CMakeLists.txt
  src/cmd/transport.bash_completion.sh
  src/ign_TEST.cc
  test/test_config.h.in
Labels: 🏰 citadel, needs upstream release, Gazebo 1️1️, OOBE 📦✨

#249 Detect ign instead of using cmake module to check for ignition-tools
  CMakeLists.txt
  test/test_config.h.in
  tools/CMakeLists.txt
  tools/ign_TEST.cc
Labels: Gazebo 9️

#322 [ign -> gz] CMake functions
  CMakeLists.txt
  conf/CMakeLists.txt
  conf/transport.yaml.in
  include/gz/transport/CMakeLists.txt
  log/include/gz/transport/CMakeLists.txt
  log/src/CMakeLists.txt
  log/test/integration/CMakeLists.txt
  src/CMakeLists.txt
  src/cmd/CMakeLists.txt
  test/integration/CMakeLists.txt
  test/performance/CMakeLists.txt
  test/regression/CMakeLists.txt
Labels: 🌱 garden, ign to gz

#319 ign -> gz Macro Migration : gz-transport
  Migration.md
  include/gz/transport/CIface.h
  include/gz/transport/Clock.hh
  include/gz/transport/Discovery.hh
  include/gz/transport/Helpers.hh
  include/ignition/transport/Helpers.hh
  log/include/gz/transport/log/Playback.hh
  log/include/gz/transport/log/Recorder.hh
  log/test/integration/playback.cc
  log/test/integration/recorder.cc
  src/NetUtils.cc
  src/Node.cc
  src/NodeShared.cc
  src/cmd/ign.cc
  src/cmd/ign.hh
  src/cmd/ign_TEST.cc
  test/test_config.h.in
Labels: needs upstream release, 🌱 garden, ign to gz

#321 ign -> gz CLI Migration : gz-transport
  CMakeLists.txt
  Changelog.md
  INSTALL_WINDOWS.md
  Migration.md
  README.md
  conf/CMakeLists.txt
  example/subscriber_stats.cc
  include/gz/transport/ReqHandler.hh
  log/src/cmd/CMakeLists.txt
  log/src/cmd/cmdlog.rb.in
  log/src/cmd/transportlog.yaml.in
  log/test/integration/CMakeLists.txt
  log/test/integration/gz_log_record_force.rb
  log/test/integration/gz_log_record_no_overwrite.rb
  src/cmd/CMakeLists.txt
  src/cmd/gz.cc
  src/cmd/gz.hh
  src/cmd/gz_TEST.cc
  src/cmd/gz_src_TEST.cc
  src/cmd/service_main.cc
  src/cmd/topic_main.cc
  tutorials/02_installation.md
  tutorials/04_messages.md
  tutorials/06_security.md
  tutorials/07_relay.md
  tutorials/10_logging.md
  tutorials/23_topic_statistics.md
Labels: 🌱 garden, ign to gz

#320 Rename CMake project to gz
  CMakeLists.txt
  example/CMakeLists.txt
  example/configure.bat
  log/test/integration/CMakeLists.txt
  src/CMakeLists.txt
  src/cmd/CMakeLists.txt
  src/cmd/gz_TEST.cc
  test/test_config.h.in
  tutorials/04_messages.md
Labels: needs upstream release, 🌱 garden, ign to gz

#324 Migrate ignition-transport
  Changelog.md
  conf/transport.yaml.in
  example/configure.bat
  example/playback.cc
  example/record.cc
  log/src/cmd/cmdlog.rb.in
  log/src/cmd/transportlog.yaml.in
  tutorials/02_installation.md
Labels: 🌱 garden

#326 Use auto for loop iterators
  src/Node.cc
Labels: 🌱 garden
