Repository gazebosim/gz-transport, pull requests merged in 2022-08, with the labels that each got.

#343 Merge ign-transport11 ➡️ main
  CMakeLists.txt
  Changelog.md
  README.md
  src/cmd/CMakeLists.txt
  src/cmd/gz_TEST.cc
  src/cmd/transport.bash_completion.sh
Labels: 🌱 garden

#345 ign -> gz : Remove redundant namespace references
  log/src/Playback.cc
  log/src/Recorder.cc
  log/src/cmd/LogCommandAPI.cc
  src/Clock_TEST.cc
  src/Discovery_TEST.cc
  src/HandlerStorage_TEST.cc
  src/NodeShared.cc
  src/Node_TEST.cc
  src/Packet.cc
  src/TopicStorage_TEST.cc
  src/ign.cc
  src/ign_TEST.cc
  src/ign_src_TEST.cc
  test/integration/authPubSub.cc
  test/integration/authPubSubSubscriberInvalid_aux.cc
  test/integration/fastPub_aux.cc
  test/integration/pub_aux.cc
  test/integration/pub_aux_throttled.cc
  test/integration/scopedTopic.cc
  test/integration/scopedTopicSubscriber_aux.cc
  test/integration/statistics.cc
  test/integration/twoProcsPubSub.cc
  test/integration/twoProcsPubSubSubscriber_aux.cc
  test/integration/twoProcsPublisher_aux.cc
  test/integration/twoProcsSrvCall.cc
  test/integration/twoProcsSrvCallReplierInc_aux.cc
  test/integration/twoProcsSrvCallReplier_aux.cc
  test/integration/twoProcsSrvCallStress.cc
  test/integration/twoProcsSrvCallSync1.cc
  test/integration/twoProcsSrvCallWithoutInput.cc
  test/integration/twoProcsSrvCallWithoutInputReplierInc_aux.cc
  test/integration/twoProcsSrvCallWithoutInputReplier_aux.cc
  test/integration/twoProcsSrvCallWithoutInputStress.cc
  test/integration/twoProcsSrvCallWithoutInputSync1.cc
  test/integration/twoProcsSrvCallWithoutOutput.cc
  test/integration/twoProcsSrvCallWithoutOutputReplierInc_aux.cc
  test/integration/twoProcsSrvCallWithoutOutputReplier_aux.cc
  test/integration/twoProcsSrvCallWithoutOutputStress.cc
Labels: 🏰 citadel

#348 🎈 11.2.0
  CMakeLists.txt
  Changelog.md
Labels: 🏯 fortress

#350 Backport Windows fix from main branch
  include/ignition/transport/TopicStatistics.hh
Labels: 🏰 citadel, Windows

#315 Don't use ignition/msgs.hh
  include/gz/transport/Node.hh
  include/gz/transport/detail/Node.hh
  log/test/integration/recorder.cc
  src/Clock.cc
  src/Clock_TEST.cc
  src/HandlerStorage_TEST.cc
  src/NodeShared.cc
  src/Node_TEST.cc
  src/cmd/gz.cc
  src/cmd/gz_TEST.cc
  src/cmd/gz_src_TEST.cc
  test/integration/authPubSub.cc
  test/integration/authPubSubSubscriberInvalid_aux.cc
  test/integration/fastPub_aux.cc
  test/integration/pub_aux.cc
  test/integration/pub_aux_throttled.cc
  test/integration/scopedTopic.cc
  test/integration/scopedTopicSubscriber_aux.cc
  test/integration/statistics.cc
  test/integration/twoProcsPubSub.cc
  test/integration/twoProcsPubSubSubscriber_aux.cc
  test/integration/twoProcsPublisher_aux.cc
  test/integration/twoProcsSrvCall.cc
  test/integration/twoProcsSrvCallReplierInc_aux.cc
  test/integration/twoProcsSrvCallReplier_aux.cc
  test/integration/twoProcsSrvCallStress.cc
  test/integration/twoProcsSrvCallSync1.cc
  test/integration/twoProcsSrvCallWithoutInput.cc
  test/integration/twoProcsSrvCallWithoutInputReplierInc_aux.cc
  test/integration/twoProcsSrvCallWithoutInputReplier_aux.cc
  test/integration/twoProcsSrvCallWithoutInputStress.cc
  test/integration/twoProcsSrvCallWithoutInputSync1.cc
  test/integration/twoProcsSrvCallWithoutOutput.cc
  test/integration/twoProcsSrvCallWithoutOutputReplierInc_aux.cc
  test/integration/twoProcsSrvCallWithoutOutputReplier_aux.cc
  test/integration/twoProcsSrvCallWithoutOutputStress.cc
Labels: bug, 🌱 garden, Breaking change
