Repository gazebosim/gz-transport, pull requests merged in 2023-11, with the labels that each got.

#453 Make empty constructor as peer to explicit
  include/gz/transport/Node.hh
  src/Node.cc
Labels: 🎵 harmonic

#457 Remove duplicated functionality from test_config
  log/test/integration/playback.cc
  log/test/integration/recorder.cc
  log/test/integration/topicChirp_aux.cc
  src/CIface_TEST.cc
  src/Discovery_TEST.cc
  src/Helpers_TEST.cc
  src/NodeOptions_TEST.cc
  src/Node_TEST.cc
  src/cmd/gz_TEST.cc
  src/cmd/gz_src_TEST.cc
  test/integration/authPubSub.cc
  test/integration/authPubSubSubscriberInvalid_aux.cc
  test/integration/fastPub_aux.cc
  test/integration/pub_aux.cc
  test/integration/pub_aux_throttled.cc
  test/integration/scopedTopic.cc
  test/integration/scopedTopicSubscriber_aux.cc
  test/integration/statistics.cc
  test/integration/twoProcsPubSub.cc
  test/integration/twoProcsPubSubSubscriber_aux.cc
  test/integration/twoProcsPublisher_aux.cc
  test/integration/twoProcsSrvCall.cc
  test/integration/twoProcsSrvCallReplierInc_aux.cc
  test/integration/twoProcsSrvCallReplier_aux.cc
  test/integration/twoProcsSrvCallStress.cc
  test/integration/twoProcsSrvCallSync1.cc
  test/integration/twoProcsSrvCallWithoutInput.cc
  test/integration/twoProcsSrvCallWithoutInputReplierInc_aux.cc
  test/integration/twoProcsSrvCallWithoutInputReplier_aux.cc
  test/integration/twoProcsSrvCallWithoutInputStress.cc
  test/integration/twoProcsSrvCallWithoutInputSync1.cc
  test/integration/twoProcsSrvCallWithoutOutput.cc
  test/integration/twoProcsSrvCallWithoutOutputReplierInc_aux.cc
  test/integration/twoProcsSrvCallWithoutOutputReplier_aux.cc
  test/integration/twoProcsSrvCallWithoutOutputStress.cc
  test/test_config.hh.in
Labels: 🌱 garden

#458 port: 12 to 13
  log/test/integration/playback.cc
  log/test/integration/recorder.cc
  log/test/integration/topicChirp_aux.cc
  src/CIface_TEST.cc
  src/Discovery_TEST.cc
  src/Helpers_TEST.cc
  src/NodeOptions_TEST.cc
  src/Node_TEST.cc
  src/cmd/gz_TEST.cc
  src/cmd/gz_src_TEST.cc
  test/integration/authPubSub.cc
  test/integration/authPubSubSubscriberInvalid_aux.cc
  test/integration/fastPub_aux.cc
  test/integration/pub_aux.cc
  test/integration/pub_aux_throttled.cc
  test/integration/scopedTopic.cc
  test/integration/scopedTopicSubscriber_aux.cc
  test/integration/statistics.cc
  test/integration/twoProcsPubSub.cc
  test/integration/twoProcsPubSubSubscriber_aux.cc
  test/integration/twoProcsPublisher_aux.cc
  test/integration/twoProcsSrvCall.cc
  test/integration/twoProcsSrvCallReplierInc_aux.cc
  test/integration/twoProcsSrvCallReplier_aux.cc
  test/integration/twoProcsSrvCallStress.cc
  test/integration/twoProcsSrvCallSync1.cc
  test/integration/twoProcsSrvCallWithoutInput.cc
  test/integration/twoProcsSrvCallWithoutInputReplierInc_aux.cc
  test/integration/twoProcsSrvCallWithoutInputReplier_aux.cc
  test/integration/twoProcsSrvCallWithoutInputStress.cc
  test/integration/twoProcsSrvCallWithoutInputSync1.cc
  test/integration/twoProcsSrvCallWithoutOutput.cc
  test/integration/twoProcsSrvCallWithoutOutputReplierInc_aux.cc
  test/integration/twoProcsSrvCallWithoutOutputReplier_aux.cc
  test/integration/twoProcsSrvCallWithoutOutputStress.cc
  test/test_config.hh.in
Labels: 🎵 harmonic

#450 Adds the python bindings tutorial
  python/examples/publisher.py
  python/examples/requester.py
  python/examples/subscriber.py
  python/src/transport/_gz_transport_pybind11.cc
  tutorials/01_intro.md
  tutorials/05_services.md
  tutorials/06_python_support.md
  tutorials/07_security.md
  tutorials/08_relay.md
Labels: 🎵 harmonic

#460 Update Github Action workflows
  .github/workflows/ci.yml
  .github/workflows/triage.yml
Labels: 🏰 citadel

#429 Use subprocess rather than custom code
  log/src/CMakeLists.txt
  log/src/Log_TEST.cc
  log/test/CMakeLists.txt
  log/test/integration/CMakeLists.txt
  log/test/integration/ChirpParams.cc
  log/test/integration/ChirpParams.hh
  log/test/integration/playback.cc
  log/test/integration/recorder.cc
  log/test/integration/topicChirp_aux.cc
  log/test/test_config.hh.in
  src/CMakeLists.txt
  src/cmd/CMakeLists.txt
  src/cmd/gz_TEST.cc
  test/integration/CMakeLists.txt
  test/integration/authPubSub.cc
  test/integration/scopedTopic.cc
  test/integration/twoProcsPubSub.cc
  test/integration/twoProcsSrvCall.cc
  test/integration/twoProcsSrvCallStress.cc
  test/integration/twoProcsSrvCallSync1.cc
  test/integration/twoProcsSrvCallWithoutInput.cc
  test/integration/twoProcsSrvCallWithoutInputStress.cc
  test/integration/twoProcsSrvCallWithoutInputSync1.cc
  test/integration/twoProcsSrvCallWithoutOutput.cc
  test/integration/twoProcsSrvCallWithoutOutputStress.cc
  test/test_config.hh.in
Labels: 🌱 garden
