Repository gazebosim/gz-transport, pull requests merged in 2023-08, with the labels that each got.

#427 Fix Github project automation for new project board
  .github/workflows/triage.yml
Labels: 🌱 garden

#423 Disable Focal on Harmonic
  .github/workflows/ci.yml
Labels: beta, 🎵 harmonic

#428 Use `pull_request_target` for triage workflow
  .github/workflows/triage.yml
Labels: 🌱 garden

#424 Remove ignition
  NEWS
  docker/gz-transport/Dockerfile
  example/record.cc
  include/CMakeLists.txt
  include/ignition/transport.hh
  include/ignition/transport/AdvertiseOptions.hh
  include/ignition/transport/CIface.h
  include/ignition/transport/Clock.hh
  include/ignition/transport/Discovery.hh
  include/ignition/transport/Export.hh
  include/ignition/transport/HandlerStorage.hh
  include/ignition/transport/Helpers.hh
  include/ignition/transport/MessageInfo.hh
  include/ignition/transport/NetUtils.hh
  include/ignition/transport/Node.hh
  include/ignition/transport/NodeOptions.hh
  include/ignition/transport/NodeShared.hh
  include/ignition/transport/Packet.hh
  include/ignition/transport/Publisher.hh
  include/ignition/transport/RepHandler.hh
  include/ignition/transport/ReqHandler.hh
  include/ignition/transport/SubscribeOptions.hh
  include/ignition/transport/SubscriptionHandler.hh
  include/ignition/transport/TopicStatistics.hh
  include/ignition/transport/TopicStorage.hh
  include/ignition/transport/TopicUtils.hh
  include/ignition/transport/TransportTypes.hh
  include/ignition/transport/Uuid.hh
  include/ignition/transport/config.hh
  include/ignition/transport/detail/Export.hh
  include/ignition/transport/detail/Node.hh
  include/ignition/transport/log.hh
  log/include/CMakeLists.txt
  log/include/ignition/transport/log/Batch.hh
  log/include/ignition/transport/log/Descriptor.hh
  log/include/ignition/transport/log/Export.hh
  log/include/ignition/transport/log/Log.hh
  log/include/ignition/transport/log/Message.hh
  log/include/ignition/transport/log/MsgIter.hh
  log/include/ignition/transport/log/Playback.hh
  log/include/ignition/transport/log/QualifiedTime.hh
  log/include/ignition/transport/log/QueryOptions.hh
  log/include/ignition/transport/log/Recorder.hh
  log/include/ignition/transport/log/SqlStatement.hh
  log/include/ignition/transport/log/detail/Export.hh
  log/include/ignition/transport/log/detail/QueryOptions.hh
  test/integration/deprecated_TEST.cc
Labels: 🎵 harmonic

#426 Remove deprecations in Harmonic
  include/gz/transport/CIface.h
  include/gz/transport/Discovery.hh
  include/gz/transport/NodeShared.hh
  log/include/gz/transport/log/Log.hh
  log/src/Log.cc
  log/test/integration/playback.cc
  log/test/integration/recorder.cc
  src/NetUtils.cc
  src/NodeOptions.cc
  src/NodeShared.cc
Labels: beta

#431 Acquire the GIL when invoking callbacks
  python/src/transport/_gz_transport_pybind11.cc
Labels: beta, 🎵 harmonic

#433 Fix python install directory
  python/CMakeLists.txt
Labels: beta, 🎵 harmonic

#432 Fix race condition in TopicInfo
  include/gz/transport/Discovery.hh
Labels: beta, 🎵 harmonic

#434 Merge gz-transport12 ➡️ main
  .github/workflows/triage.yml
  parameters/src/Client_TEST.cc
  parameters/src/cmd/ParamCommandAPI_TEST.cc
Labels: 🎵 harmonic
