Repository gazebosim/gz-transport, pull requests merged in 2024-01, with the labels that each got.

#466 🎈 8.5.0
  CMakeLists.txt
  Changelog.md
Labels: 🏰 citadel

#467 Remove HIDE_SYMBOLS_BY_DEFAULT: replace by a default configuration in gz-cmake.
  CMakeLists.txt
Labels: 🏛️ ionic

#469 Merge ign-transport8 ➡️ ign-transport11
  .github/workflows/ci.yml
  .github/workflows/triage.yml
  Changelog.md
  src/cmd/transport.bash_completion.sh
Labels: 🏯 fortress

#471 Merge ign-transport11 ➡️ gz-transport12
  .github/workflows/ci.yml
  .github/workflows/triage.yml
  Changelog.md
  src/cmd/transport.bash_completion.sh
Labels: 🌱 garden

#463 Test refactoring part 2
  log/test/integration/playback.cc
  log/test/integration/recorder.cc
  src/CMakeLists.txt
  src/Discovery_TEST.cc
  src/cmd/CMakeLists.txt
  src/cmd/gz_TEST.cc
  test/CMakeLists.txt
  test/integration/CMakeLists.txt
  test/integration/authPubSub.cc
  test/integration/scopedTopic.cc
  test/integration/statistics.cc
  test/integration/test_executables/authPubSubSubscriberInvalid_aux.cc
  test/integration/test_executables/fastPub_aux.cc
  test/integration/test_executables/pub_aux.cc
  test/integration/test_executables/pub_aux_throttled.cc
  test/integration/test_executables/scopedTopicSubscriber_aux.cc
  test/integration/test_executables/twoProcsPubSubSubscriber_aux.cc
  test/integration/test_executables/twoProcsPublisher_aux.cc
  test/integration/test_executables/twoProcsSrvCallReplierInc_aux.cc
  test/integration/test_executables/twoProcsSrvCallReplier_aux.cc
  test/integration/test_executables/twoProcsSrvCallWithoutInputReplierInc_aux.cc
  test/integration/test_executables/twoProcsSrvCallWithoutInputReplier_aux.cc
  test/integration/test_executables/twoProcsSrvCallWithoutOutputReplierInc_aux.cc
  test/integration/test_executables/twoProcsSrvCallWithoutOutputReplier_aux.cc
  test/integration/twoProcsPubSub.cc
  test/integration/twoProcsSrvCall.cc
  test/integration/twoProcsSrvCallStress.cc
  test/integration/twoProcsSrvCallSync1.cc
  test/integration/twoProcsSrvCallWithoutInput.cc
  test/integration/twoProcsSrvCallWithoutInputStress.cc
  test/integration/twoProcsSrvCallWithoutInputSync1.cc
  test/integration/twoProcsSrvCallWithoutOutput.cc
  test/integration/twoProcsSrvCallWithoutOutputStress.cc
  test/test_config.hh.in
  test/test_utils.hh
Labels: 🌱 garden
