Repository gazebosim/gz-transport, pull requests merged in 2024-08, with the labels that each got.

#513 Merge 13 -> main
  .github/workflows/package_xml.yml
  Changelog.md
  include/gz/transport/SubscribeOptions.hh
  include/gz/transport/SubscriptionHandler.hh
  package.xml
  src/Node.cc
  src/NodeShared.cc
  src/NodeSharedPrivate.hh
  src/Node_TEST.cc
  src/SubscribeOptions.cc
  src/SubscribeOptionsPrivate.hh
  src/SubscriptionHandler.cc
  src/cmd/gz.cc
  src/cmd/gz.hh
  src/cmd/topic_main.cc
  tutorials.md.in
Labels: 🏛️ ionic

#512 Add an explicit dependency on cppzmq-dev
  .github/ci/packages-noble.apt
Labels: beta, 🏛️ ionic

#515 IGN_IP -> GZ_IP
  include/gz/transport/Discovery.hh
Labels: 🎵 harmonic

#517 Disable playback.ReplayStep for windows
  log/test/integration/playback.cc
Labels: 🏰 citadel

#518 8 :arrow_right: 11
  log/test/integration/playback.cc
Labels: 🏯 fortress

#516 Added Prerequisites section in file
  tutorials/06_python_support.md
Labels: documentation, 🎵 harmonic

#521 11 :arrow_right: 12 - Disable playback.ReplayStep for windows (#517)
  log/test/integration/playback.cc
Labels: 🌱 garden

#522 12 :arrow_right: 13 - Disable playback.ReplayStep for windows (#517)
  log/test/integration/playback.cc
Labels: 🎵 harmonic

#524 Update gz-transport14 badge URLs
  Changelog.md
  README.md
Labels: 🏛️ ionic

#525 Prepare for 14.0.0~pre1 release
  CMakeLists.txt
  Changelog.md
Labels: 🏛️ ionic

#526 Fix installation tutorial links
  tutorials/01_intro.md
Labels: 🏛️ ionic

#527 Ionic: Installation tutorial fixes
  tutorials/02_installation.md
Labels: 🏛️ ionic

#528 Ionic: Python tutorial updates
  tutorials/06_python_support.md
Labels: 🏛️ ionic
