Repository gazebosim/gz-transport, pull requests merged in 2024-11, with the labels that each got.

#550 Using Pathname to check for absolute path in ruby script
  src/cmd/cmdtransport.rb.in
Labels: 🏛️ ionic

#541 Add compatibility with protobuf 28
  include/gz/transport/RepHandler.hh
  include/gz/transport/SubscriptionHandler.hh
Labels: 🏛️ ionic

#551 Fix flakiness in the TopicInfo test
  src/cmd/gz_TEST.cc
Labels: 🏯 fortress

#553 Prepare for 12.2.2 Release
  CMakeLists.txt
  Changelog.md
Labels: 🌱 garden

#554 Permit building python bindings separately from main library
  CMakeLists.txt
  python/CMakeLists.txt
  tutorials/02_installation.md
Labels: 🏛️ ionic, 🪵 jetty
