Repository gazebosim/gz-transport, pull requests merged in 2025-04, with the labels that each got.

#603 Support cmake 4.0
  python/CMakeLists.txt
Labels: 🏛️ ionic, 🪵 jetty

#606 Remove duplicate cmake_minimum_required
  python/CMakeLists.txt
Labels: 🏛️ ionic, 🪵 jetty

#607 Cast nanoseconds to int64_t
  log/src/QueryOptions.cc
Labels: 🏛️ ionic, 🪵 jetty

#616 Disable Jammy CI
  .github/workflows/ci.yml
  log/include/gz/transport/log/MsgIter.hh
Labels: 🪵 jetty

#617 ci: run cppcheck, cpplint, doxygen on noble
  .github/workflows/ci.yml
  log/include/gz/transport/log/MsgIter.hh
Labels: 🏛️ ionic

#615 Fix compatibility with protobuf v30 (cpp 6.30.0) - similar to gz-msgs #499
  include/gz/transport/RepHandler.hh
  include/gz/transport/ReqHandler.hh
  include/gz/transport/SubscriptionHandler.hh
  include/gz/transport/detail/Node.hh
  parameters/src/Client.cc
  parameters/src/Registry.cc
  src/CIface_TEST.cc
  src/HandlerStorage_TEST.cc
  src/Node.cc
  src/Node_TEST.cc
  src/cmd/gz.cc
  src/cmd/gz_TEST.cc
  test/integration/test_executables/twoProcsPubSubSingleSubscriber_aux.cc
  test/integration/test_executables/twoProcsPubSubSubscriber_aux.cc
  test/integration/twoProcsPubSub.cc
Labels: 🪵 jetty
